### ISSUE TITLE
About customizing the settings for font display

### ISSUE THREAD

**Issue by taotieren** [RosiePuddles/mdbook-compress#1]
Hello. I want to customize the font displayed by PDF. How to set it up? Thank you.

**Comment by v-nxe** [comment]
currently, you can't. i'm working on some highlighting at the moment but i should be able to add that in in a bit

**Comment by v-nxe** [comment]
added in for v0.2.1 which is now released. hope it works okay for you. make sure to use .ttf or possibly .otf font files (font file must be readable by rusttype)

**Comment by taotieren** [comment]
Thank you very much. I can help you pack it to AUR [mdbook-compress](https://aur.archlinux.org/packages/mdbook-compress) repo later.
