### ISSUE TITLE
The PDF is not created and no error

### ISSUE THREAD

**Issue by sspaeti** [RosiePuddles/mdbook-compress#4]
First of all, thanks for the work. It seems it is what I need to create a physical book out of my Markdown.

Unfortunately, when I install and add  `[output.compress]` to my `book.toml` and run:

```sh
❯ mdbook build
2024-03-19 11:56:56 [INFO] (mdbook::book): Book building has started
2024-03-19 11:56:56 [INFO] (mdbook::book): Running the compress backend
2024-03-19 11:56:56 [INFO] (mdbook::renderer): Invoking the "compress" renderer
2024-03-19 11:56:56 [INFO] (mdbook::book): Running the html backend

❯ ls book/compress
empty
```

The renderer was triggered (see above), but nothing has been generated. 
Also, if I try to run the `mdbook-compress` only, it hangs with no return or error.

How would I debug or see any error? Or am I doing something wrong? I added different configs to book.toml, but nothing worked. Any help would be much appreciated.

```sh
❯ mdbook --version
mdbook v0.4.37

❯ cargo install mdbook-compress --force
....
   Replacing /Users/sspaeti/.cargo/bin/mdbook-compress
    Replaced package `mdbook-compress v0.2.1` with `mdbook-compress v0.2.1` (executable `mdbook-compress`)
```

**Comment by v-nxe** [comment]
i'm going to try get a dev branch set up. i'll try to get the code on there to be really verbose so it might give some indication what it's doing. then try fix te issue from there

**Comment by v-nxe** [comment]
c8bb756 should allow you to see in more detail what's happening. if you could run that and then put the log here i'll see if i can fix the issue

you should be able to install it with
```sh
cargo install --git "https://github.com/RosiePuddles/mdbook-compress" --branch "dev"
```

**Comment by sspaeti** [comment]
Thanks so much @RosiePuddles. That worked, now I see the errors. I get some highlight errors of code as it looks like. Just a couple of them:

```
Error highlighting code! Using un-highlighted code. Could not find the language 'import pandas as pd
```
and
```
                                                                                                                                                                                                                                                                                                                       

Error: Unknown language: "DECLARE
   CURSOR c1 is
      SELECT ename, empno, sal FROM emp
         ORDER BY sal DESC;   -- start with highest paid employee
   my_ename VARCHAR2(10);
   my_empno NUMBER(4);
   my_sal   NUMBER(7,2);
BEGIN
   OPEN c1;
   FOR i IN 1..5 LOOP
      FETCH c1 INTO my_ename, my_empno, my_sal;
      EXIT WHEN c1%NOTFOUND;  /* in case the number requested */
                              /* is more than the total       */
                              /* number of employees          */
      INSERT INTO temp VALUES (my_sal, my_empno, my_ename);
      COMMIT;
   END LOOP;
   CLOSE c1;
END;
"
    at m ([eval]:6:8960)
    at Object.b [as highlight] ([eval]:6:6251)
    at [eval]:53:19068
    at runScriptInThisContext (node:internal/vm:144:10)
    at node:internal/process/execution:109:14
    at [eval]-wrapper:6:24
    at runScript (node:internal/process/execution:92:62)
    at evalScript (node:internal/process/execution:123:10)
    at node:internal/main/eval_string:51:3

Node.js v21.6.2
```
These are code samples I have inside my book.

But it actually generated a PDF this time, even tough some errors occurred. So I guess you fixed it too. I will dig a bit deeper when I have some time. Thank you so much for this effort. Love it!

**Comment by v-nxe** [comment]
that to me seems like an issue with your markdown. it's expecting three backticks followed by the language (optional) with the actual code on the lines after it. the first issue seems like you've got the code starting on the same line as the backticks. not so sure about the second error though. looks similar but quite different at the same time

**Comment by sspaeti** [comment]
I will dig deeper later, but the PDF was created, and I also got the error, so I'm super happy. Everything is working now. Again, thanks so much, and I will close the issue.

**Comment by v-nxe** [comment]
i've finally got around to going back to this project nad having a proper look at it. you mnay be experiencing a lot of hanging time in the program (30+ seconds) from highliting related code. i'm going to try to rework a lot of the project which should make this much faster i hope
